Ejercicio del clase

In [9]:
import pandas as pd

Crear data frame

In [3]:
motos = {
    "Marca": ["Ducati" , "AKT", "Yamaha" , "BMW"],
    "Cilindraje": [600,150,100,1200],
    "Modelo" : [2015,2018,2026,2022]
}
df = pd.DataFrame(motos)
display(df)

    Marca  Cilindraje  Modelo
0  Ducati         600    2015
1     AKT         150    2018
2  Yamaha         100    2026
3     BMW        1200    2022

In [4]:
print(df["Marca"][2])

Yamaha

Reemplazar valor

In [5]:
df["Marca"][1] = "Honda"
df["Modelo"] = [199,1995,1993,1998]
display(df)

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_14344\3370333080.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["Marca"][1] = "Honda"
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_14344\3370333080.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Marca"][1] = "Honda"

    Marca  Cilindraje  Modelo
0  Ducati         600     199
1   Honda         150    1995
2  Yamaha         100    1993
3     BMW        1200    1998

In [6]:
df.loc[1,"cilindraje"]= 500
display(df)

    Marca  Cilindraje  Modelo  cilindraje
0  Ducati         600     199         NaN
1   Honda         150    1995       500.0
2  Yamaha         100    1993         NaN
3     BMW        1200    1998         NaN

Agregar columna

In [7]:
df["color"] = ["Negro","Azul","Verde","Rojo"]
display(df)

    Marca  Cilindraje  Modelo  cilindraje  color
0  Ducati         600     199         NaN  Negro
1   Honda         150    1995       500.0   Azul
2  Yamaha         100    1993         NaN  Verde
3     BMW        1200    1998         NaN   Rojo

Agregar un elemento

In [8]:
df.loc[len(df)] = ["Susuki",800,2000,"Gris"]
display(df)

ValueError: cannot set a row with mismatched columns

24 abril 2026

In [10]:
list_columns =["Nombre", "Poblacion" , "Area" , "Moneda"]
list_data = [
    ["Colombia" , 50, 1100,"Peso"],
    ["Brasil", 120, 8500, "Real"],
    ["España", 50, 500 ,"Euro"]
]
df_data = pd.DataFrame(data=list_data, columns=list_columns)
display(df_data)

     Nombre  Poblacion  Area Moneda
0  Colombia         50  1100   Peso
1    Brasil        120  8500   Real
2    España         50   500   Euro

crear data frame con los datos

In [12]:
list_columns = ["Producto","Precio","Cantidad"]
list_data = [
    ["Manzanas" , 3000 , 10],
    ["Peras", 2500 , 5],
    ["Bananas", 2000 , 8],
    ["Mandarina", 3000, 12],
    ["Naranjas", 2000 , 20],
    ["Fresas", 2500 , 7]
]
df_data = pd.DataFrame(data=list_data , columns=list_columns)
display(df_data)

    Producto  Precio  Cantidad
0   Manzanas    3000        10
1      Peras    2500         5
2    Bananas    2000         8
3  Mandarina    3000        12
4   Naranjas    2000        20
5     Fresas    2500         7

2. Agregar columna valor total

In [ ]:

df["valor total"] = [int]
display(df)