In [43]:
import pandas as pd

Crear DataFrame

In [44]:
list_columns = ["Producto","Precio","Cantidad"]
list_data = [
    ["Manzanas" , 3000 , 10],
    ["Peras", 2500 , 5],
    ["Bananas", 2000 , 8],
    ["Mandarina", 3000, 12],
    ["Naranjas", 2000 , 20],
    ["Fresas", 2500 , 7]
]
df_data = pd.DataFrame(data=list_data , columns=list_columns)
display(df_data)

    Producto  Precio  Cantidad
0   Manzanas    3000        10
1      Peras    2500         5
2    Bananas    2000         8
3  Mandarina    3000        12
4   Naranjas    2000        20
5     Fresas    2500         7

Agregar columna valor total

In [45]:

df_data["valor total"] = df_data["Precio"]* df_data["Cantidad"]
display(df_data)

    Producto  Precio  Cantidad  valor total
0   Manzanas    3000        10        30000
1      Peras    2500         5        12500
2    Bananas    2000         8        16000
3  Mandarina    3000        12        36000
4   Naranjas    2000        20        40000
5     Fresas    2500         7        17500

Filtrar las ventas mayores a 20.000

In [46]:
df_filtrar = df_data[df_data["valor total"] > 20000]
display(df_filtrar)

    Producto  Precio  Cantidad  valor total
0   Manzanas    3000        10        30000
3  Mandarina    3000        12        36000
4   Naranjas    2000        20        40000

Determinar el producto con mayor ventas

In [54]:
pos_max = df_data["valor total"].idxmax()
print(df_data.loc[pos_max,"Producto"])

Naranjas

Agregar ua columna descuento 10 %

In [53]:
df_data["Descuento"] = (df_data["valor total"] * 0.1).astype(int)
display(df_data)

    Producto  Precio  Cantidad  valor total  Descuento
0   Manzanas    3000        10        30000       3000
1      Peras    2500         5        12500       1250
2    Bananas    2000         8        16000       1600
3  Mandarina    3000        12        36000       3600
4   Naranjas    2000        20        40000       4000
5     Fresas    2500         7        17500       1750

Obtener ventas totales

In [59]:
total = df_data["valor total"].sum()
print(total)

152000

Obetener promedio

In [70]:
promedio_ventas = round(df_data["valor total"].mean(), 2)
print(promedio_ventas)

25333.33

Obtener data frame de mayor a menor

In [71]:
df_ordenado = df_data.sort_values("valor total" , ascending=False)
display(df_ordenado)

    Producto  Precio  Cantidad  valor total  Descuento
4   Naranjas    2000        20        40000       4000
3  Mandarina    3000        12        36000       3600
0   Manzanas    3000        10        30000       3000
5     Fresas    2500         7        17500       1750
2    Bananas    2000         8        16000       1600
1      Peras    2500         5        12500       1250