In [110]:
import pandas as pd

Importar Excel

In [111]:
df_peliculas = pd.read_excel("data_peliculas.xlsx")
display(df_peliculas)

   Peliculas                 Nombre   Año       Genero   Presupuesto
0        NaN                Avengers  2010       Acción          400
1        NaN                     saw  2018       Terror          100
2        NaN                    cars  2006   Animacion            20
3        NaN  Donde estan las rubias  2000      Comedia           15
4        NaN         Michael Jackson  2026  Documental            50

Importar CVS

In [112]:
df_peliculas_2= pd.read_csv("Data_peliculas.csv")
display(df_peliculas_2)

   Peliculas                 Nombre   Año       Genero   Presupuesto
0        NaN                Avengers  2010       Acción          400
1        NaN                     saw  2018       Terror          100
2        NaN                    cars  2006   Animacion            20
3        NaN  Donde estan las rubias  2000      Comedia           15
4        NaN         Michael Jackson  2026  Documental            50

Agregar columna director y exportar

In [113]:

df_peliculas["Director"] = ["Andrea","Carlos","Maria","Jonier","Juan"]
display(df_peliculas)

   Peliculas                 Nombre   Año       Genero   Presupuesto Director
0        NaN                Avengers  2010       Acción          400   Andrea
1        NaN                     saw  2018       Terror          100   Carlos
2        NaN                    cars  2006   Animacion            20    Maria
3        NaN  Donde estan las rubias  2000      Comedia           15   Jonier
4        NaN         Michael Jackson  2026  Documental            50     Juan

In [114]:
df_peliculas.to_excel("nuevo_archivo.xlsx")

In [115]:
df_peliculas_2.to_csv("nuevo_archivo_2.csv")

Trabajo en clase, importar archivo CSV

In [116]:
df_personas = pd.read_csv(r"C:\Users\USUARIO\Downloads\Ejercicio de clase - Hoja 1.csv",header=1)
display(df_personas)

,Unnamed: 0,Unnamed: 1,Nombre,Apellido,Edad,Género,Nivel educativo
0,NaN,NaN,Andres,Mancera,17,Masculino,Bachiller
1,NaN,NaN,Carlos,Perez,25,Indefinido,Bachiller
2,NaN,NaN,Emilia,Garzon,35,Femenino,Universitario
3,NaN,NaN,Juan,Montoya,23,M,Tecnologo
4,NaN,NaN,Sara,Pardo,26,f,profesional
5,NaN,NaN,María,Lopez,45,F,secundaria
6,NaN,NaN,juan,perez,36,m,Universitario
7,NaN,NaN,ANA,GOMEZ,NaN,Femenino,universidad
8,NaN,NaN,Pedro,NaN,abc,M,primaria
9,NaN,NaN,Luisa,Torres,X,NaN,bachillerato
10,NaN,NaN,carlos,ramirez,NaN,M,uni
11,NaN,NaN,Marta,Diaz,200,F,Secundaria
12,NaN,NaN,NaN,Herrera,NaN,F,secundaria
13,NaN,NaN,Diego,Ruiz,57,Masculino,Universidad
14,NaN,NaN,Sofia,Castro,NaN,F,doctorado
15,NaN,NaN,Andres,Lopez123,3459,M,secundaria
16,NaN,NaN,Laura,Perez,0.5,F,sec
17,NaN,NaN,Felipe,Gomez,0,M,NaN
18,NaN,NaN,Camila,Rojas,g,femenino,Universitaria
19,NaN,NaN,roberto,Sanchez,b,m,bachiller
20,NaN,NaN,Oscar,Cañas,NaN,M,Universidad
21,NaN,NaN,Valentina,Martínez,19,F,Secundaria
22,NaN,NaN,sebastian,gomez,17,m,bachillerato
23,NaN,NaN,ANDRES,ROJAS,22,Masculino,Universidad
24,NaN,NaN,Paula,Lopez,NaN,F,sec
25,NaN,NaN,Jorge,Diaz,twenty,M,universitario
26,NaN,NaN,Daniela,Castro,21,femenino,Uni
27,NaN,NaN,Miguel,Suarez,18,M,secundaria
28,NaN,NaN,Lucia,fernandez,20,F,Universitaria
29,NaN,NaN,Santiago,Martinez,16,m,primaria
30,NaN,NaN,Camilo,Garcia,19,Masculino,bachiller
31,NaN,NaN,Elena,Ruiz,18,F,Sec
32,NaN,NaN,Oscar,Lopez,25,M,doctorado
33,NaN,NaN,Natalia,Pérez,20,NaN,Universidad
34,NaN,NaN,Ricardo,Sanchez,23,M,uni
35,NaN,NaN,Patricia,Gomez,21,F,secundaria
36,NaN,NaN,Alberto,Hernandez,abc,M,Secundaria
37,NaN,NaN,Monica,Diaz,19,Femenino,NaN
38,NaN,NaN,Fernando,Castro,17,m,bachiller
39,NaN,NaN,Julian,Ramirez,22,M,Universidad
40,NaN,NaN,Gabriela,Torres,20,F,universitaria

Eliminar columnas vacias

In [117]:
df_personas.drop(columns=["Unnamed: 1"] , inplace=True)
display(df_personas)

    Unnamed: 0     Nombre   Apellido    Edad      Género Nivel educativo
0          NaN     Andres    Mancera      17   Masculino       Bachiller
1          NaN     Carlos      Perez      25  Indefinido       Bachiller
2          NaN     Emilia     Garzon      35    Femenino   Universitario
3          NaN       Juan    Montoya      23           M       Tecnologo
4          NaN       Sara      Pardo      26           f     profesional
5          NaN      María      Lopez      45           F      secundaria
6          NaN       juan      perez      36           m   Universitario
7          NaN        ANA      GOMEZ     NaN    Femenino     universidad
8          NaN      Pedro        NaN     abc           M        primaria
9          NaN      Luisa     Torres       X         NaN    bachillerato
10         NaN     carlos    ramirez     NaN           M             uni
11         NaN      Marta       Diaz     200           F      Secundaria
12         NaN        NaN    Herrera     NaN           F      secundaria
13         NaN      Diego       Ruiz      57   Masculino     Universidad
14         NaN      Sofia     Castro     NaN           F       doctorado
15         NaN     Andres   Lopez123    3459           M      secundaria
16         NaN      Laura      Perez     0.5           F             sec
17         NaN     Felipe      Gomez       0           M             NaN
18         NaN     Camila      Rojas       g    femenino   Universitaria
19         NaN    roberto    Sanchez       b           m       bachiller
20         NaN      Oscar      Cañas     NaN           M     Universidad
21         NaN  Valentina   Martínez      19           F      Secundaria
22         NaN  sebastian      gomez      17           m    bachillerato
23         NaN     ANDRES      ROJAS      22   Masculino     Universidad
24         NaN      Paula      Lopez     NaN           F             sec
25         NaN      Jorge       Diaz  twenty           M   universitario
26         NaN    Daniela     Castro      21    femenino             Uni
27         NaN     Miguel     Suarez      18           M      secundaria
28         NaN      Lucia  fernandez      20           F   Universitaria
29         NaN   Santiago   Martinez      16           m        primaria
30         NaN     Camilo     Garcia      19   Masculino       bachiller
31         NaN      Elena       Ruiz      18           F             Sec
32         NaN      Oscar      Lopez      25           M       doctorado
33         NaN    Natalia      Pérez      20         NaN     Universidad
34         NaN    Ricardo    Sanchez      23           M             uni
35         NaN   Patricia      Gomez      21           F      secundaria
36         NaN    Alberto  Hernandez     abc           M      Secundaria
37         NaN     Monica       Diaz      19    Femenino             NaN
38         NaN   Fernando     Castro      17           m       bachiller
39         NaN     Julian    Ramirez      22           M     Universidad
40         NaN   Gabriela     Torres      20           F   universitaria

Quitar la tilde y el nombre de la tabla sin espacio

In [118]:
df_personas.rename(columns={'Género' : 'Genero','Nivel educativo':'Nivel_educativo'}, inplace=True)
display(df_personas)

    Unnamed: 0     Nombre   Apellido    Edad      Genero Nivel_educativo
0          NaN     Andres    Mancera      17   Masculino       Bachiller
1          NaN     Carlos      Perez      25  Indefinido       Bachiller
2          NaN     Emilia     Garzon      35    Femenino   Universitario
3          NaN       Juan    Montoya      23           M       Tecnologo
4          NaN       Sara      Pardo      26           f     profesional
5          NaN      María      Lopez      45           F      secundaria
6          NaN       juan      perez      36           m   Universitario
7          NaN        ANA      GOMEZ     NaN    Femenino     universidad
8          NaN      Pedro        NaN     abc           M        primaria
9          NaN      Luisa     Torres       X         NaN    bachillerato
10         NaN     carlos    ramirez     NaN           M             uni
11         NaN      Marta       Diaz     200           F      Secundaria
12         NaN        NaN    Herrera     NaN           F      secundaria
13         NaN      Diego       Ruiz      57   Masculino     Universidad
14         NaN      Sofia     Castro     NaN           F       doctorado
15         NaN     Andres   Lopez123    3459           M      secundaria
16         NaN      Laura      Perez     0.5           F             sec
17         NaN     Felipe      Gomez       0           M             NaN
18         NaN     Camila      Rojas       g    femenino   Universitaria
19         NaN    roberto    Sanchez       b           m       bachiller
20         NaN      Oscar      Cañas     NaN           M     Universidad
21         NaN  Valentina   Martínez      19           F      Secundaria
22         NaN  sebastian      gomez      17           m    bachillerato
23         NaN     ANDRES      ROJAS      22   Masculino     Universidad
24         NaN      Paula      Lopez     NaN           F             sec
25         NaN      Jorge       Diaz  twenty           M   universitario
26         NaN    Daniela     Castro      21    femenino             Uni
27         NaN     Miguel     Suarez      18           M      secundaria
28         NaN      Lucia  fernandez      20           F   Universitaria
29         NaN   Santiago   Martinez      16           m        primaria
30         NaN     Camilo     Garcia      19   Masculino       bachiller
31         NaN      Elena       Ruiz      18           F             Sec
32         NaN      Oscar      Lopez      25           M       doctorado
33         NaN    Natalia      Pérez      20         NaN     Universidad
34         NaN    Ricardo    Sanchez      23           M             uni
35         NaN   Patricia      Gomez      21           F      secundaria
36         NaN    Alberto  Hernandez     abc           M      Secundaria
37         NaN     Monica       Diaz      19    Femenino             NaN
38         NaN   Fernando     Castro      17           m       bachiller
39         NaN     Julian    Ramirez      22           M     Universidad
40         NaN   Gabriela     Torres      20           F   universitaria

elimnar nulo

In [119]:
df_personas = df_personas.dropna(subset=["Nombre","Apellido"])
display(df_personas)

    Unnamed: 0     Nombre   Apellido    Edad      Genero Nivel_educativo
0          NaN     Andres    Mancera      17   Masculino       Bachiller
1          NaN     Carlos      Perez      25  Indefinido       Bachiller
2          NaN     Emilia     Garzon      35    Femenino   Universitario
3          NaN       Juan    Montoya      23           M       Tecnologo
4          NaN       Sara      Pardo      26           f     profesional
5          NaN      María      Lopez      45           F      secundaria
6          NaN       juan      perez      36           m   Universitario
7          NaN        ANA      GOMEZ     NaN    Femenino     universidad
9          NaN      Luisa     Torres       X         NaN    bachillerato
10         NaN     carlos    ramirez     NaN           M             uni
11         NaN      Marta       Diaz     200           F      Secundaria
13         NaN      Diego       Ruiz      57   Masculino     Universidad
14         NaN      Sofia     Castro     NaN           F       doctorado
15         NaN     Andres   Lopez123    3459           M      secundaria
16         NaN      Laura      Perez     0.5           F             sec
17         NaN     Felipe      Gomez       0           M             NaN
18         NaN     Camila      Rojas       g    femenino   Universitaria
19         NaN    roberto    Sanchez       b           m       bachiller
20         NaN      Oscar      Cañas     NaN           M     Universidad
21         NaN  Valentina   Martínez      19           F      Secundaria
22         NaN  sebastian      gomez      17           m    bachillerato
23         NaN     ANDRES      ROJAS      22   Masculino     Universidad
24         NaN      Paula      Lopez     NaN           F             sec
25         NaN      Jorge       Diaz  twenty           M   universitario
26         NaN    Daniela     Castro      21    femenino             Uni
27         NaN     Miguel     Suarez      18           M      secundaria
28         NaN      Lucia  fernandez      20           F   Universitaria
29         NaN   Santiago   Martinez      16           m        primaria
30         NaN     Camilo     Garcia      19   Masculino       bachiller
31         NaN      Elena       Ruiz      18           F             Sec
32         NaN      Oscar      Lopez      25           M       doctorado
33         NaN    Natalia      Pérez      20         NaN     Universidad
34         NaN    Ricardo    Sanchez      23           M             uni
35         NaN   Patricia      Gomez      21           F      secundaria
36         NaN    Alberto  Hernandez     abc           M      Secundaria
37         NaN     Monica       Diaz      19    Femenino             NaN
38         NaN   Fernando     Castro      17           m       bachiller
39         NaN     Julian    Ramirez      22           M     Universidad
40         NaN   Gabriela     Torres      20           F   universitaria

In [120]:
df_personas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 39 entries, 0 to 40
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       0 non-null      float64
 1   Nombre           39 non-null     object
 2   Apellido         39 non-null     object
 3   Edad             34 non-null     object
 4   Genero           37 non-null     object
 5   Nivel_educativo  37 non-null     object
dtypes: float64(1), object(5)
memory usage: 2.1+ KB

todos los string volverlo a none

In [121]:
df_personas.loc[9, "Edad"] = None
df_personas.loc[18, "Edad"] = None
df_personas.loc[19, "Edad"] = None
df_personas.loc[25, "Edad"] = None
df_personas.loc[36, "Edad"] = None
display(df_personas)

    Unnamed: 0     Nombre   Apellido  Edad      Genero Nivel_educativo
0          NaN     Andres    Mancera    17   Masculino       Bachiller
1          NaN     Carlos      Perez    25  Indefinido       Bachiller
2          NaN     Emilia     Garzon    35    Femenino   Universitario
3          NaN       Juan    Montoya    23           M       Tecnologo
4          NaN       Sara      Pardo    26           f     profesional
5          NaN      María      Lopez    45           F      secundaria
6          NaN       juan      perez    36           m   Universitario
7          NaN        ANA      GOMEZ   NaN    Femenino     universidad
9          NaN      Luisa     Torres  None         NaN    bachillerato
10         NaN     carlos    ramirez   NaN           M             uni
11         NaN      Marta       Diaz   200           F      Secundaria
13         NaN      Diego       Ruiz    57   Masculino     Universidad
14         NaN      Sofia     Castro   NaN           F       doctorado
15         NaN     Andres   Lopez123  3459           M      secundaria
16         NaN      Laura      Perez   0.5           F             sec
17         NaN     Felipe      Gomez     0           M             NaN
18         NaN     Camila      Rojas  None    femenino   Universitaria
19         NaN    roberto    Sanchez  None           m       bachiller
20         NaN      Oscar      Cañas   NaN           M     Universidad
21         NaN  Valentina   Martínez    19           F      Secundaria
22         NaN  sebastian      gomez    17           m    bachillerato
23         NaN     ANDRES      ROJAS    22   Masculino     Universidad
24         NaN      Paula      Lopez   NaN           F             sec
25         NaN      Jorge       Diaz  None           M   universitario
26         NaN    Daniela     Castro    21    femenino             Uni
27         NaN     Miguel     Suarez    18           M      secundaria
28         NaN      Lucia  fernandez    20           F   Universitaria
29         NaN   Santiago   Martinez    16           m        primaria
30         NaN     Camilo     Garcia    19   Masculino       bachiller
31         NaN      Elena       Ruiz    18           F             Sec
32         NaN      Oscar      Lopez    25           M       doctorado
33         NaN    Natalia      Pérez    20         NaN     Universidad
34         NaN    Ricardo    Sanchez    23           M             uni
35         NaN   Patricia      Gomez    21           F      secundaria
36         NaN    Alberto  Hernandez  None           M      Secundaria
37         NaN     Monica       Diaz    19    Femenino             NaN
38         NaN   Fernando     Castro    17           m       bachiller
39         NaN     Julian    Ramirez    22           M     Universidad
40         NaN   Gabriela     Torres    20           F   universitaria

In [122]:
df_personas["Edad"] = df_personas["Edad"].astype("Float64")
df_personas["Edad"] = df_personas["Edad"].astype("Int64")
display(df_personas)

    Unnamed: 0     Nombre   Apellido  Edad      Genero Nivel_educativo
0          NaN     Andres    Mancera    17   Masculino       Bachiller
1          NaN     Carlos      Perez    25  Indefinido       Bachiller
2          NaN     Emilia     Garzon    35    Femenino   Universitario
3          NaN       Juan    Montoya    23           M       Tecnologo
4          NaN       Sara      Pardo    26           f     profesional
5          NaN      María      Lopez    45           F      secundaria
6          NaN       juan      perez    36           m   Universitario
7          NaN        ANA      GOMEZ  <NA>    Femenino     universidad
9          NaN      Luisa     Torres  <NA>         NaN    bachillerato
10         NaN     carlos    ramirez  <NA>           M             uni
11         NaN      Marta       Diaz   200           F      Secundaria
13         NaN      Diego       Ruiz    57   Masculino     Universidad
14         NaN      Sofia     Castro  <NA>           F       doctorado
15         NaN     Andres   Lopez123  3459           M      secundaria
16         NaN      Laura      Perez     0           F             sec
17         NaN     Felipe      Gomez     0           M             NaN
18         NaN     Camila      Rojas  <NA>    femenino   Universitaria
19         NaN    roberto    Sanchez  <NA>           m       bachiller
20         NaN      Oscar      Cañas  <NA>           M     Universidad
21         NaN  Valentina   Martínez    19           F      Secundaria
22         NaN  sebastian      gomez    17           m    bachillerato
23         NaN     ANDRES      ROJAS    22   Masculino     Universidad
24         NaN      Paula      Lopez  <NA>           F             sec
25         NaN      Jorge       Diaz  <NA>           M   universitario
26         NaN    Daniela     Castro    21    femenino             Uni
27         NaN     Miguel     Suarez    18           M      secundaria
28         NaN      Lucia  fernandez    20           F   Universitaria
29         NaN   Santiago   Martinez    16           m        primaria
30         NaN     Camilo     Garcia    19   Masculino       bachiller
31         NaN      Elena       Ruiz    18           F             Sec
32         NaN      Oscar      Lopez    25           M       doctorado
33         NaN    Natalia      Pérez    20         NaN     Universidad
34         NaN    Ricardo    Sanchez    23           M             uni
35         NaN   Patricia      Gomez    21           F      secundaria
36         NaN    Alberto  Hernandez  <NA>           M      Secundaria
37         NaN     Monica       Diaz    19    Femenino             NaN
38         NaN   Fernando     Castro    17           m       bachiller
39         NaN     Julian    Ramirez    22           M     Universidad
40         NaN   Gabriela     Torres    20           F   universitaria

Promedio de la edad

In [123]:
promedio_edad = round(df_personas["Edad"].mean(), 2)
print(promedio_edad)

146.9

Reemplazo de valores

In [124]:
df_personas["Genero"].replace({"M":"Masculino", "F":"Femenino", "m":"Masculino", "f":"Femenino", "Indefinido": None}, inplace=True)
display(df_personas)

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_3536\533650975.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_personas["Genero"].replace({"M":"Masculino", "F":"Femenino", "m":"Masculino", "f":"Femenino", "Indefinido": None}, inplace=True)

    Unnamed: 0     Nombre   Apellido  Edad     Genero Nivel_educativo
0          NaN     Andres    Mancera    17  Masculino       Bachiller
1          NaN     Carlos      Perez    25       None       Bachiller
2          NaN     Emilia     Garzon    35   Femenino   Universitario
3          NaN       Juan    Montoya    23  Masculino       Tecnologo
4          NaN       Sara      Pardo    26   Femenino     profesional
5          NaN      María      Lopez    45   Femenino      secundaria
6          NaN       juan      perez    36  Masculino   Universitario
7          NaN        ANA      GOMEZ  <NA>   Femenino     universidad
9          NaN      Luisa     Torres  <NA>        NaN    bachillerato
10         NaN     carlos    ramirez  <NA>  Masculino             uni
11         NaN      Marta       Diaz   200   Femenino      Secundaria
13         NaN      Diego       Ruiz    57  Masculino     Universidad
14         NaN      Sofia     Castro  <NA>   Femenino       doctorado
15         NaN     Andres   Lopez123  3459  Masculino      secundaria
16         NaN      Laura      Perez     0   Femenino             sec
17         NaN     Felipe      Gomez     0  Masculino             NaN
18         NaN     Camila      Rojas  <NA>   femenino   Universitaria
19         NaN    roberto    Sanchez  <NA>  Masculino       bachiller
20         NaN      Oscar      Cañas  <NA>  Masculino     Universidad
21         NaN  Valentina   Martínez    19   Femenino      Secundaria
22         NaN  sebastian      gomez    17  Masculino    bachillerato
23         NaN     ANDRES      ROJAS    22  Masculino     Universidad
24         NaN      Paula      Lopez  <NA>   Femenino             sec
25         NaN      Jorge       Diaz  <NA>  Masculino   universitario
26         NaN    Daniela     Castro    21   femenino             Uni
27         NaN     Miguel     Suarez    18  Masculino      secundaria
28         NaN      Lucia  fernandez    20   Femenino   Universitaria
29         NaN   Santiago   Martinez    16  Masculino        primaria
30         NaN     Camilo     Garcia    19  Masculino       bachiller
31         NaN      Elena       Ruiz    18   Femenino             Sec
32         NaN      Oscar      Lopez    25  Masculino       doctorado
33         NaN    Natalia      Pérez    20        NaN     Universidad
34         NaN    Ricardo    Sanchez    23  Masculino             uni
35         NaN   Patricia      Gomez    21   Femenino      secundaria
36         NaN    Alberto  Hernandez  <NA>  Masculino      Secundaria
37         NaN     Monica       Diaz    19   Femenino             NaN
38         NaN   Fernando     Castro    17  Masculino       bachiller
39         NaN     Julian    Ramirez    22  Masculino     Universidad
40         NaN   Gabriela     Torres    20   Femenino   universitaria

contar

In [125]:
df_femeninos = df_personas[df_personas["Genero"] == "Femenino"]
display(df_femeninos)
cantidad_femenino = df_femeninos["Genero"].count()
print("La cantidad de mujeres es:", cantidad_femenino)

    Unnamed: 0     Nombre   Apellido  Edad    Genero Nivel_educativo
2          NaN     Emilia     Garzon    35  Femenino   Universitario
4          NaN       Sara      Pardo    26  Femenino     profesional
5          NaN      María      Lopez    45  Femenino      secundaria
7          NaN        ANA      GOMEZ  <NA>  Femenino     universidad
11         NaN      Marta       Diaz   200  Femenino      Secundaria
14         NaN      Sofia     Castro  <NA>  Femenino       doctorado
16         NaN      Laura      Perez     0  Femenino             sec
21         NaN  Valentina   Martínez    19  Femenino      Secundaria
24         NaN      Paula      Lopez  <NA>  Femenino             sec
28         NaN      Lucia  fernandez    20  Femenino   Universitaria
31         NaN      Elena       Ruiz    18  Femenino             Sec
35         NaN   Patricia      Gomez    21  Femenino      secundaria
37         NaN     Monica       Diaz    19  Femenino             NaN
40         NaN   Gabriela     Torres    20  Femenino   universitaria

La cantidad de mujeres es: 14

In [126]:
df_masculinos = df_personas[df_personas["Genero"] == "Masculino"]
display(df_masculinos)
cantidad_masculino = df_masculinos["Genero"].count()
print("La cantidad de hombres es:", cantidad_masculino)

    Unnamed: 0     Nombre   Apellido  Edad     Genero Nivel_educativo
0          NaN     Andres    Mancera    17  Masculino       Bachiller
3          NaN       Juan    Montoya    23  Masculino       Tecnologo
6          NaN       juan      perez    36  Masculino   Universitario
10         NaN     carlos    ramirez  <NA>  Masculino             uni
13         NaN      Diego       Ruiz    57  Masculino     Universidad
15         NaN     Andres   Lopez123  3459  Masculino      secundaria
17         NaN     Felipe      Gomez     0  Masculino             NaN
19         NaN    roberto    Sanchez  <NA>  Masculino       bachiller
20         NaN      Oscar      Cañas  <NA>  Masculino     Universidad
22         NaN  sebastian      gomez    17  Masculino    bachillerato
23         NaN     ANDRES      ROJAS    22  Masculino     Universidad
25         NaN      Jorge       Diaz  <NA>  Masculino   universitario
27         NaN     Miguel     Suarez    18  Masculino      secundaria
29         NaN   Santiago   Martinez    16  Masculino        primaria
30         NaN     Camilo     Garcia    19  Masculino       bachiller
32         NaN      Oscar      Lopez    25  Masculino       doctorado
34         NaN    Ricardo    Sanchez    23  Masculino             uni
36         NaN    Alberto  Hernandez  <NA>  Masculino      Secundaria
38         NaN   Fernando     Castro    17  Masculino       bachiller
39         NaN     Julian    Ramirez    22  Masculino     Universidad

La cantidad de hombres es: 20

In [127]:
data = df_personas.groupby("Genero")["Nombre"].count()
print(data)

Genero
Femenino     14
Masculino    20
femenino      2
Name: Nombre, dtype: int64

Poner mayusculas

In [128]:
df_personas["Nombre"] = df_personas["Nombre"].str.capitalize()
df_personas["Apellido"] = df_personas["Apellido"].str.capitalize()
df_personas

    Unnamed: 0     Nombre   Apellido  Edad     Genero Nivel_educativo
0          NaN     Andres    Mancera    17  Masculino       Bachiller
1          NaN     Carlos      Perez    25       None       Bachiller
2          NaN     Emilia     Garzon    35   Femenino   Universitario
3          NaN       Juan    Montoya    23  Masculino       Tecnologo
4          NaN       Sara      Pardo    26   Femenino     profesional
5          NaN      María      Lopez    45   Femenino      secundaria
6          NaN       Juan      Perez    36  Masculino   Universitario
7          NaN        Ana      Gomez  <NA>   Femenino     universidad
9          NaN      Luisa     Torres  <NA>        NaN    bachillerato
10         NaN     Carlos    Ramirez  <NA>  Masculino             uni
11         NaN      Marta       Diaz   200   Femenino      Secundaria
13         NaN      Diego       Ruiz    57  Masculino     Universidad
14         NaN      Sofia     Castro  <NA>   Femenino       doctorado
15         NaN     Andres   Lopez123  3459  Masculino      secundaria
16         NaN      Laura      Perez     0   Femenino             sec
17         NaN     Felipe      Gomez     0  Masculino             NaN
18         NaN     Camila      Rojas  <NA>   femenino   Universitaria
19         NaN    Roberto    Sanchez  <NA>  Masculino       bachiller
20         NaN      Oscar      Cañas  <NA>  Masculino     Universidad
21         NaN  Valentina   Martínez    19   Femenino      Secundaria
22         NaN  Sebastian      Gomez    17  Masculino    bachillerato
23         NaN     Andres      Rojas    22  Masculino     Universidad
24         NaN      Paula      Lopez  <NA>   Femenino             sec
25         NaN      Jorge       Diaz  <NA>  Masculino   universitario
26         NaN    Daniela     Castro    21   femenino             Uni
27         NaN     Miguel     Suarez    18  Masculino      secundaria
28         NaN      Lucia  Fernandez    20   Femenino   Universitaria
29         NaN   Santiago   Martinez    16  Masculino        primaria
30         NaN     Camilo     Garcia    19  Masculino       bachiller
31         NaN      Elena       Ruiz    18   Femenino             Sec
32         NaN      Oscar      Lopez    25  Masculino       doctorado
33         NaN    Natalia      Pérez    20        NaN     Universidad
34         NaN    Ricardo    Sanchez    23  Masculino             uni
35         NaN   Patricia      Gomez    21   Femenino      secundaria
36         NaN    Alberto  Hernandez  <NA>  Masculino      Secundaria
37         NaN     Monica       Diaz    19   Femenino             NaN
38         NaN   Fernando     Castro    17  Masculino       bachiller
39         NaN     Julian    Ramirez    22  Masculino     Universidad
40         NaN   Gabriela     Torres    20   Femenino   universitaria

In [129]:
df_personas["Nivel_educativo"].replace({"universitario":"Universidad", "bachiller":"Bachillerato", "sec":"Bachillerato", "secundaria":"Bachillerato", "uni": "Universidad"} , inplace=True)
display(df_personas)

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_3536\3912892555.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_personas["Nivel_educativo"].replace({"universitario":"Universidad", "bachiller":"Bachillerato", "sec":"Bachillerato", "secundaria":"Bachillerato", "uni": "Universidad"} , inplace=True)

    Unnamed: 0     Nombre   Apellido  Edad     Genero Nivel_educativo
0          NaN     Andres    Mancera    17  Masculino       Bachiller
1          NaN     Carlos      Perez    25       None       Bachiller
2          NaN     Emilia     Garzon    35   Femenino   Universitario
3          NaN       Juan    Montoya    23  Masculino       Tecnologo
4          NaN       Sara      Pardo    26   Femenino     profesional
5          NaN      María      Lopez    45   Femenino    Bachillerato
6          NaN       Juan      Perez    36  Masculino   Universitario
7          NaN        Ana      Gomez  <NA>   Femenino     universidad
9          NaN      Luisa     Torres  <NA>        NaN    bachillerato
10         NaN     Carlos    Ramirez  <NA>  Masculino     Universidad
11         NaN      Marta       Diaz   200   Femenino      Secundaria
13         NaN      Diego       Ruiz    57  Masculino     Universidad
14         NaN      Sofia     Castro  <NA>   Femenino       doctorado
15         NaN     Andres   Lopez123  3459  Masculino    Bachillerato
16         NaN      Laura      Perez     0   Femenino    Bachillerato
17         NaN     Felipe      Gomez     0  Masculino             NaN
18         NaN     Camila      Rojas  <NA>   femenino   Universitaria
19         NaN    Roberto    Sanchez  <NA>  Masculino    Bachillerato
20         NaN      Oscar      Cañas  <NA>  Masculino     Universidad
21         NaN  Valentina   Martínez    19   Femenino      Secundaria
22         NaN  Sebastian      Gomez    17  Masculino    bachillerato
23         NaN     Andres      Rojas    22  Masculino     Universidad
24         NaN      Paula      Lopez  <NA>   Femenino    Bachillerato
25         NaN      Jorge       Diaz  <NA>  Masculino     Universidad
26         NaN    Daniela     Castro    21   femenino             Uni
27         NaN     Miguel     Suarez    18  Masculino    Bachillerato
28         NaN      Lucia  Fernandez    20   Femenino   Universitaria
29         NaN   Santiago   Martinez    16  Masculino        primaria
30         NaN     Camilo     Garcia    19  Masculino    Bachillerato
31         NaN      Elena       Ruiz    18   Femenino             Sec
32         NaN      Oscar      Lopez    25  Masculino       doctorado
33         NaN    Natalia      Pérez    20        NaN     Universidad
34         NaN    Ricardo    Sanchez    23  Masculino     Universidad
35         NaN   Patricia      Gomez    21   Femenino    Bachillerato
36         NaN    Alberto  Hernandez  <NA>  Masculino      Secundaria
37         NaN     Monica       Diaz    19   Femenino             NaN
38         NaN   Fernando     Castro    17  Masculino    Bachillerato
39         NaN     Julian    Ramirez    22  Masculino     Universidad
40         NaN   Gabriela     Torres    20   Femenino   universitaria

In [130]:
print(df_personas["Nivel_educativo"].str.contains("Univer"))

0     False
1     False
2      True
3     False
4     False
5     False
6      True
7     False
9     False
10     True
11    False
13     True
14    False
15    False
16    False
17      NaN
18     True
19    False
20     True
21    False
22    False
23     True
24    False
25     True
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34     True
35    False
36    False
37      NaN
38    False
39     True
40    False
Name: Nivel_educativo, dtype: object

In [132]:
df_personas.loc[df_personas["Nivel_educativo"].str.contains("Uni", na=False), "Nivel_educativo"]= "Universidad"
df_personas.loc[df_personas["Nivel_educativo"].str.contains("Bach", na=False), "Nivel_educativo"]= "Bachillerato"
df_personas.loc[df_personas["Nivel_educativo"].str.contains("Sec", na=False), "Nivel_educativo"] = "Secundaria"
display(df_personas)

    Unnamed: 0     Nombre   Apellido  Edad     Genero Nivel_educativo
0          NaN     Andres    Mancera    17  Masculino    Bachillerato
1          NaN     Carlos      Perez    25       None    Bachillerato
2          NaN     Emilia     Garzon    35   Femenino     Universidad
3          NaN       Juan    Montoya    23  Masculino       Tecnologo
4          NaN       Sara      Pardo    26   Femenino     profesional
5          NaN      María      Lopez    45   Femenino    Bachillerato
6          NaN       Juan      Perez    36  Masculino     Universidad
7          NaN        Ana      Gomez  <NA>   Femenino     universidad
9          NaN      Luisa     Torres  <NA>        NaN    bachillerato
10         NaN     Carlos    Ramirez  <NA>  Masculino     Universidad
11         NaN      Marta       Diaz   200   Femenino      Secundaria
13         NaN      Diego       Ruiz    57  Masculino     Universidad
14         NaN      Sofia     Castro  <NA>   Femenino       doctorado
15         NaN     Andres   Lopez123  3459  Masculino    Bachillerato
16         NaN      Laura      Perez     0   Femenino    Bachillerato
17         NaN     Felipe      Gomez     0  Masculino             NaN
18         NaN     Camila      Rojas  <NA>   femenino     Universidad
19         NaN    Roberto    Sanchez  <NA>  Masculino    Bachillerato
20         NaN      Oscar      Cañas  <NA>  Masculino     Universidad
21         NaN  Valentina   Martínez    19   Femenino      Secundaria
22         NaN  Sebastian      Gomez    17  Masculino    bachillerato
23         NaN     Andres      Rojas    22  Masculino     Universidad
24         NaN      Paula      Lopez  <NA>   Femenino    Bachillerato
25         NaN      Jorge       Diaz  <NA>  Masculino     Universidad
26         NaN    Daniela     Castro    21   femenino     Universidad
27         NaN     Miguel     Suarez    18  Masculino    Bachillerato
28         NaN      Lucia  Fernandez    20   Femenino     Universidad
29         NaN   Santiago   Martinez    16  Masculino        primaria
30         NaN     Camilo     Garcia    19  Masculino    Bachillerato
31         NaN      Elena       Ruiz    18   Femenino      Secundaria
32         NaN      Oscar      Lopez    25  Masculino       doctorado
33         NaN    Natalia      Pérez    20        NaN     Universidad
34         NaN    Ricardo    Sanchez    23  Masculino     Universidad
35         NaN   Patricia      Gomez    21   Femenino    Bachillerato
36         NaN    Alberto  Hernandez  <NA>  Masculino      Secundaria
37         NaN     Monica       Diaz    19   Femenino             NaN
38         NaN   Fernando     Castro    17  Masculino    Bachillerato
39         NaN     Julian    Ramirez    22  Masculino     Universidad
40         NaN   Gabriela     Torres    20   Femenino   universitaria

In [133]:
df_personas.to_excel("data_clean.xlsx",index=False)