In [2]:
import pandas as pd

In [4]:
list_columns = ["Producto","Precio","Cantidad"]
list_data = [
    ["Manzanas" , 3000 , 10],
    ["Peras", 2500 , 5],
    ["Bananas", 2000 , 8],
    ["Mandarina", 3000, 12],
    ["Naranjas", 2000 , 20],
    ["Fresas", 2500 , 7]
]
df_data = pd.DataFrame(data=list_data , columns=list_columns)
display(df_data)

    Producto  Precio  Cantidad
0   Manzanas    3000        10
1      Peras    2500         5
2    Bananas    2000         8
3  Mandarina    3000        12
4   Naranjas    2000        20
5     Fresas    2500         7

Creacion y modificacion de columnas

In [8]:
df_data.rename(columns={"Producto":"Productos"}, inplace=True)
display(df_data)

   Productos  Precio  Cantidad
0   Manzanas    3000        10
1      Peras    2500         5
2    Bananas    2000         8
3  Mandarina    3000        12
4   Naranjas    2000        20
5     Fresas    2500         7

Eliminacion de una columna

In [20]:
df_data = df_data.drop(columns=["Cantidad"])
display(df_data)

   Productos  Precio
0   Manzanas    3000
1      Peras    2500
2    Bananas    2000
3  Mandarina    3000
4   Naranjas    2000
5     Fresas    2500

Orden de datos

In [21]:
df_data = df_data.sort_values("Precio", ascending=True)
display(df_data)

   Productos  Precio
2    Bananas    2000
4   Naranjas    2000
5     Fresas    2500
1      Peras    2500
3  Mandarina    3000
0   Manzanas    3000

Manejo de valores faltantes

In [22]:
df_data.loc[len(df_data)] = ["Mangos", None]
display(df_data)

   Productos Precio
2    Bananas   2000
4   Naranjas   2000
5     Fresas   2500
1      Peras   2500
3  Mandarina   3000
0   Manzanas   3000
6     Mangos   None

In [24]:
print(df_data.isnull().sum())
df_data = df_data.dropna(subset=["Precio"])
display(df_data)

Productos    0
Precio       1
dtype: int64

   Productos Precio
2    Bananas   2000
4   Naranjas   2000
5     Fresas   2500
1      Peras   2500
3  Mandarina   3000
0   Manzanas   3000

In [26]:
df_data.loc[len(df_data)] = ["Bananas", 0]
display(df_data)

   Productos Precio
2    Bananas   2000
4   Naranjas   2000
5     Fresas   2500
1      Peras   2500
3  Mandarina   3000
0   Manzanas   3000
6    Bananas   None
7    Bananas      0

In [28]:
df_data["Precio"].fillna(0)
display(df_data)

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_10160\3405730953.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_data["Precio"].fillna(0)

   Productos Precio
2    Bananas   2000
4   Naranjas   2000
5     Fresas   2500
1      Peras   2500
3  Mandarina   3000
0   Manzanas   3000
6    Bananas   None
7    Bananas      0

Eliminar duplicados

In [30]:
df_data.loc[len(df_data)] = ["Bananas", 2000]
display(df_data)

   Productos Precio
2    Bananas   2000
4   Naranjas   2000
5     Fresas   2500
1      Peras   2500
3  Mandarina   3000
0   Manzanas   3000
6    Bananas   None
7    Bananas      0
8    Bananas      0
9    Bananas   2000

In [31]:
df_data.drop_duplicates(inplace=True)
display(df_data)

   Productos Precio
2    Bananas   2000
4   Naranjas   2000
5     Fresas   2500
1      Peras   2500
3  Mandarina   3000
0   Manzanas   3000
6    Bananas   None
7    Bananas      0