In [11]:
import pandas as pd

Inspeccion de datos

In [2]:
list_columns = ["Raza","Color","Peso"]
list_data = [
    ["Pincher" , "caramelo" , 6],
    ["Doberman", "Negro" , 20],
    ["Chow chow", "Cafe" , 10],
    ["Golden Retriver", "Cafe" , 12],
    
]
df_mascotas = pd.DataFrame(data=list_data , columns=list_columns)
display(df_mascotas)

              Raza     Color  Peso
0          Pincher  caramelo     6
1         Doberman     Negro    20
2        Chow chow      Cafe    10
3  Golden Retriver      Cafe    12

Metodo  head

In [3]:
display(df_mascotas.head(2))

       Raza     Color  Peso
0   Pincher  caramelo     6
1  Doberman     Negro    20

Método info

In [4]:
display(df_mascotas.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Raza    4 non-null      object
 1   Color   4 non-null      object
 2   Peso    4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

None

Método describe

In [5]:
display(df_mascotas["Raza"].describe())

count           4
unique          4
top       Pincher
freq            1
Name: Raza, dtype: object

Método shape

In [6]:
display(df_mascotas.shape)

(4, 3)

Selección y filtrado

In [7]:
conteo = df_mascotas[["Raza", "Color"]]
display(conteo)

              Raza     Color
0          Pincher  caramelo
1         Doberman     Negro
2        Chow chow      Cafe
3  Golden Retriver      Cafe

Indices

In [8]:
list_inices = ["Raza","Color","Peso"]
list_columns = ["Raza","Color","Peso"]
list_data = [
    ["Pincher" , "caramelo" , 6],
    ["Doberman", "Negro" , 20],
    ["Chow chow", "Cafe" , 10],
    ["Golden Retriver", "Cafe" , 12],
    
]
df_mascotas = pd.DataFrame(data=list_data , columns=list_columns)
display(df_mascotas)

              Raza     Color  Peso
0          Pincher  caramelo     6
1         Doberman     Negro    20
2        Chow chow      Cafe    10
3  Golden Retriver      Cafe    12

In [9]:
print(df_mascotas.loc["Raza"])

KeyError: 'Raza'